# Generated by Django 5.2.5 on 2025-08-11 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='sports',
        ),
        migrations.AlterField(
            model_name='venue',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='venues.location'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='operational_hours',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='venue',
            name='photos_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='venue',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Amenity',
        ),
        migrations.AddField(
            model_name='venue',
            name='amenities',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='Sport',
        ),
        migrations.AddField(
            model_name='venue',
            name='sports',
            field=models.JSONField(default=list),
        ),
    ]
