# Generated by Django 5.2.5 on 2025-08-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_remove_venue_amenities_remove_venue_sports_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
