# Generated by Django 5.2.5 on 2025-08-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar_user_otp_code_user_otp_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('FACILITY', 'Facility_User'), ('ADMIN', 'Admin')], default='USER', max_length=20),
        ),
    ]
