# Generated by Django 5.2.5 on 2025-08-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('FACILITY', 'Facility'), ('ADMIN', 'Admin')], default='USER', max_length=20),
        ),
    ]
